(defun protocol-template ()
  (interactive)
  (let* ((title (read-string "Protokoll Überschrift: "))
         (date (format-time-string "%Y-%m-%d"))
         (buffer-name (concat date "-" title ".org")))
    (switch-to-buffer buffer-name)
    (org-mode)
;;    (set-visited-file-name buffer-name)
    (insert "#+title: " title "\n")
    (insert "#+date: " date "\n")
    (insert "#+author: " user-full-name "\n\n")))
